### ISSUE TITLE
Is AudioKit 4.2.3 compatible with Swift 4.0 and Xcode 9.2?

### ISSUE THREAD

**Issue by ladislas** [AudioKit/AudioKit#1324]
Hi there! 

The latest version of Xcode 9.3 introduced some strange compilation errors (not related to AudioKit) in the app I'm working on, which forced us to roll back to Xcode 9.2 and Swift 4.0.

Updating AudioKit 4.1 to 4.2.3 generates the following error for AudioKit:

> Module compiled with Swift 4.1 cannot be imported in Swift 4.0.3

I'm wondering if it is possible to use the latest version of AudioKit with Xcode 9.2? 

As a side note, using AudioKit 4.1 works well.

Thanks a lot for your kind help!

**Comment by megastep** [comment]
We only provide compiled binaries built with the current non-beta version of Xcode. As such, 4.2.3 was built with Xcode 9.3 and requires Swift 4.1.

If AK 4.1 works for your needs, then you should probably stick with that as long as it works in Xcode 9.2. Alternatively, you could try to build the framework from source using our provided script.

**Comment by ladislas** [comment]
Thanks! I eventually managed to fix my issue and I'm back to Xcode 9.3 and AudioKit 4.2.3!

**Comment by ryanthon** [comment]
@ladislas Curious, how did you get version 4.2.3 working with Xcode 9.3?

**Comment by ryanthon** [comment]
@ladislas Oh whoops, for some reason I read your comment as "4.0.3", and was wondering how you got it to build. Never mind!
