### PR TITLE
Added convertCompressed for visionOS 2.0

### PR DESCRIPTION
**Pull request by Matt54**
Hides existing convertCompressed from visionOS since it does not compile on the platform and adds a modern concurrency version of convertCompressed which works with visionOS 2.0

Related:
https://github.com/AudioKit/AudioKit/issues/2921
https://github.com/AudioKit/AudioKit/pull/2923

### CODE REVIEW

**Review by aure — APPROVED** [review]

**Review by aure — APPROVED** [review]

**Comment by warpling** [comment]
Would love to see this merged before 2.0 releases if possible! Thanks @Matt54 and @aure!

**Comment by aure** [comment]
> Would love to see this merged before 2.0 releases if possible! Thanks @Matt54 and @aure!

Converter/FormatConverter+Compressed.swift:86:33: error: argument passed to call that takes no arguments
        try await session.export(to: outputURL, as: outputFileType)
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

on iOS. @Matt54

**Comment by Matt54** [comment]
> > Would love to see this merged before 2.0 releases if possible! Thanks @Matt54 and @aure!
> 
> Converter/FormatConverter+Compressed.swift:86:33: error: argument passed to call that takes no arguments try await session.export(to: outputURL, as: outputFileType) ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> on iOS. @Matt54

Ahhhh of coarse! It doesn't compile if you're not on Xcode 16. Let me see what I can do

**Comment by Matt54** [comment]
I've made it compile by Swift checking it against 6.0 @aure

**Comment by Matt54** [comment]
I guess our options here are to either delete the new convertCompressed method or leave it to become available once AudioKit hits Swift 6.0

I don't care either way - seems inconsequential. We're just trying to fix visionOS
